"""Initial migration

Revision ID: fefce5238632
Revises: 
Create Date: 2026-08-26 19:15:12.616671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fefce5238632'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Books', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Books', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Books', type_='foreignkey')
    op.drop_column('Books', 'owner_id')
    # ### end Alembic commands ###
